#!/usr/bin/env python3

import os
import re
import subprocess

# KEXTs from iOS 18.1 beta 5

entries = [
    # iPhone17,1 specific
    "com.apple.driver.AppleBSDKextStarterTMPFS",
    "com.apple.driver.AppleBSDKextStarterVPN",
    "com.apple.driver.AppleHIDKeyboardEmbedded",
    "com.apple.driver.AppleStorageDrivers",
    "com.apple.driver.AppleThunderboltEDMService",
    "com.apple.driver.AppleTopCaseDriverV2",
    "com.apple.driver.SCSIDeviceSpecifics",
    "com.apple.driver.USBStorageDeviceSpecifics",
    "com.apple.driver.usb.AppleUSBHostPlatformProperties",
    "com.apple.driver.usb.IOUSBHostHIDDeviceSafeBoot",
    "com.apple.iokit.IOHIDEventDriver",
    "com.apple.iokit.IOHIDEventDriverSafeBoot",
    "com.apple.kpi.bsd",
    "com.apple.kpi.dsep",
    "com.apple.kpi.iokit",
    "com.apple.kpi.libkern",
    "com.apple.kpi.mach",
    "com.apple.kpi.private",
    "com.apple.kpi.unsupported",
    "com.apple.AGXFirmwareKextG17PRTBuddy",
    "com.apple.AGXFirmwareKextRTBuddy64",
    "com.apple.AGXG17P",
    "com.apple.driver.AOPAudio2",
    "com.apple.driver.AOPTouchKext",
    "com.apple.driver.ASIOKit",
    "com.apple.AUC",
    "com.apple.driver.AppleA7IOP-ASCWrap-v6",
    "com.apple.driver.AppleA7IOP",
    "com.apple.driver.AppleALSColorSensor",
    "com.apple.driver.AppleAOP2",
    "com.apple.driver.AppleAOPAudio",
    "com.apple.iokit.AppleARMIISAudio",
    "com.apple.driver.AppleARMPMU",
    "com.apple.driver.AppleARMPlatform",
    "com.apple.driver.AppleARMWatchdogTimer",
    "com.apple.driver.AppleAVD",
    "com.apple.driver.AppleAVE2",
    "com.apple.driver.AppleActuatorDriver",
    "com.apple.driver.AppleAstrisGpioProbe",
    "com.apple.driver.AppleAudioClockLibs",
    "com.apple.driver.AppleAuthCP",
    "com.apple.driver.AppleBSDKextStarter",
    "com.apple.driver.AppleBasebandM20",
    "com.apple.driver.AppleBasebandPCI",
    "com.apple.driver.AppleBasebandPCIMAVControl",
    "com.apple.driver.AppleBasebandPCIMAVPDP",
    "com.apple.driver.AppleBluetoothDebug",
    "com.apple.driver.AppleBluetoothDebugService",
    "com.apple.driver.AppleBluetoothModule",
    "com.apple.driver.AppleC26Charger",
    "com.apple.driver.AppleCSEmbeddedAudio",
    "com.apple.driver.AppleCallbackPowerSource",
    "com.apple.driver.AppleConvergedIPCOLYBTControl",
    "com.apple.driver.AppleConvergedPCI",
    "com.apple.driver.AppleDAPF",
    "com.apple.driver.AppleDCP",
    "com.apple.driver.AppleDCPDPTXProxy",
    "com.apple.driver.AppleDiagnosticDataAccessReadOnly",
    "com.apple.driver.AppleDialogPMU",
    "com.apple.driver.AppleDiskImages2",
    "com.apple.driver.AppleDisplayCrossbar",
    "com.apple.driver.AppleDockChannel",
    "com.apple.driver.AppleEffaceableBlockDevice",
    "com.apple.driver.AppleEffaceableStorage",
    "com.apple.driver.AppleEmbeddedAudio",
    "com.apple.driver.AppleAOPHaptics",
    "com.apple.driver.AppleCS42L79Audio",
    "com.apple.driver.IOPAudioSpeaker",
    "com.apple.driver.IOPEmbeddedAudio",
    "com.apple.driver.IOPHaptics",
    "com.apple.driver.AppleEmbeddedAudioLibs",
    "com.apple.driver.AppleEmbeddedAudioResourceManager",
    "com.apple.driver.AppleEmbeddedGPS",
    "com.apple.driver.AppleEmbeddedLightSensor",
    "com.apple.driver.AppleEmbeddedMikeyBus",
    "com.apple.driver.AppleEmbeddedPCIE",
    "com.apple.driver.AppleEmbeddedTempSensor",
    "com.apple.driver.AppleEmbeddedTouchEEPROM",
    "com.apple.driver.AppleEmbeddedUSB",
    "com.apple.driver.AppleEmbeddedUSBHost",
    "com.apple.kec.AppleEncryptedArchive",
    "com.apple.driver.AppleEpochManager",
    "com.apple.driver.AppleEventLogHandler",
    "com.apple.driver.AppleEverestErrorHandler",
    "com.apple.driver.AppleFAN53740",
    "com.apple.AppleFSCompression.AppleFSCompressionTypeZlib",
    "com.apple.driver.AppleFirmwareKit",
    "com.apple.driver.AppleFirmwareUpdateKext",
    "com.apple.driver.AppleGPIOCanary",
    "com.apple.driver.AppleGPIOICController",
    "com.apple.driver.AppleGameControllerPersonality",
    "com.apple.driver.AppleGenericMultitouch",
    "com.apple.driver.AppleH10PearlCameraInterface",
    "com.apple.driver.AppleH16ANEInterface",
    "com.apple.driver.AppleH16CameraInterface",
    "com.apple.driver.AppleH16PhotonDetector",
    "com.apple.driver.AppleHIDALSService",
    "com.apple.driver.AppleHIDKeyboard",
    "com.apple.driver.AppleHIDTransport",
    "com.apple.driver.AppleHIDTransportFIFO",
    "com.apple.driver.AppleHIDTransportSPI",
    "com.apple.driver.AppleHPM",
    "com.apple.driver.AppleHapticsSupportLEAP",
    "com.apple.driver.AppleHapticsSupportNVM",
    "com.apple.driver.AppleIDAMInterface",
    "com.apple.driver.AppleIDV",
    "com.apple.driver.AppleIISController",
    "com.apple.driver.AppleIOPADMAStream",
    "com.apple.driver.AppleIPAppender",
    "com.apple.security.AppleImage4",
    "com.apple.driver.AppleInputDeviceSupport",
    "com.apple.driver.AppleInterruptControllerV3",
    "com.apple.driver.AppleJPEGDriver",
    "com.apple.driver.AppleLockdownMode",
    "com.apple.driver.AppleM2ScalerCSCDriver",
    "com.apple.driver.AppleM68Buttons",
    "com.apple.kext.AppleMatch",
    "com.apple.driver.AppleMikeyBusAudio",
    "com.apple.driver.AppleMobileApNonce",
    "com.apple.driver.AppleMobileDispH17P-DCP",
    "com.apple.driver.AppleMobileFileIntegrity",
    "com.apple.driver.AppleMultiFunctionManager",
    "com.apple.driver.AppleMultitouchDriver",
    "com.apple.driver.AppleMultitouchSPI",
    "com.apple.driver.AppleNANDConfigAccess",
    "com.apple.driver.AppleOLYHAL",
    "com.apple.driver.AppleOnboardSerial",
    "com.apple.driver.ApplePMGR",
    "com.apple.driver.ApplePMP",
    "com.apple.driver.ApplePMPFirmware",
    "com.apple.driver.ApplePPMCPMS",
    "com.apple.driver.ApplePTD",
    "com.apple.driver.AppleParrot",
    "com.apple.driver.ApplePearlSEPDriver",
    "com.apple.driver.ApplePhoneBTM",
    "com.apple.driver.ApplePhotonDetector",
    "com.apple.driver.AppleProResHW",
    "com.apple.driver.AppleProxDriver",
    "com.apple.driver.AppleS5L8920XPWM",
    "com.apple.driver.AppleS5L8940XI2C",
    "com.apple.driver.AppleS5L8960XNCO",
    "com.apple.driver.AppleS8000AES",
    "com.apple.driver.AppleS8000DWI",
    "com.apple.driver.AppleSARService",
    "com.apple.driver.AppleSART",
    "com.apple.driver.AppleSEPCredentialManager",
    "com.apple.iokit.AppleSEPGenericTransfer",
    "com.apple.driver.AppleSEPHDCPManager",
    "com.apple.driver.AppleSEPKeyStore",
    "com.apple.driver.AppleSEPManager",
    "com.apple.driver.AppleSMC",
    "com.apple.driver.AppleSMCWirelessCharger",
    "com.apple.driver.AppleSPIMC",
    "com.apple.driver.AppleSPMI",
    "com.apple.driver.AppleSPMIPMU",
    "com.apple.driver.AppleSPU",
    "com.apple.driver.AppleSPURose",
    "com.apple.driver.AppleSPUSphere",
    "com.apple.driver.AppleSSE",
    "com.apple.driver.AppleSamsungSerial",
    "com.apple.driver.AppleSerialShim",
    "com.apple.driver.AppleSmartBatteryManagerEmbedded",
    "com.apple.driver.AppleSmartIO2",
    "com.apple.driver.AppleStockholmControl",
    "com.apple.driver.AppleUSBCardReader",
    "com.apple.driver.AppleUSBMassStorageInterfaceNub",
    "com.apple.driver.AppleSynopsysMIPIDSI",
    "com.apple.driver.AppleT8030SOCTuner",
    "com.apple.driver.AppleT8110DART",
    "com.apple.driver.AppleT8140",
    "com.apple.driver.AppleT8140ANEHAL",
    "com.apple.driver.AppleT8140CLPC",
    "com.apple.driver.AppleT8140MCC",
    "com.apple.driver.AppleT8140PCIe",
    "com.apple.driver.AppleT8140PMGR",
    "com.apple.driver.AppleTemperatureSensor",
    "com.apple.driver.AppleThunderboltDPAdapterFamily",
    "com.apple.driver.AppleThunderboltDPInAdapter",
    "com.apple.driver.AppleThunderboltDPOutAdapter",
    "com.apple.driver.AppleThunderboltEDMSource",
    "com.apple.driver.AppleThunderboltIP",
    "com.apple.driver.AppleThunderboltNHI",
    "com.apple.driver.AppleThunderboltPCIDownAdapter",
    "com.apple.driver.AppleThunderboltPCIUpAdapter",
    "com.apple.driver.AppleThunderboltUSBDownAdapter",
    "com.apple.driver.AppleThunderboltUSBUpAdapter",
    "com.apple.driver.AppleTopCaseHIDEventDriver",
    "com.apple.driver.AppleUSBTopCaseDriver",
    "com.apple.driver.AppleTriStar",
    "com.apple.driver.AppleTypeCPhy",
    "com.apple.driver.AppleT8103TypeCPhy",
    "com.apple.driver.AppleT8130TypeCPhy",
    "com.apple.driver.AppleTypeCPhyAUSBC",
    "com.apple.driver.AppleUSBAudio",
    "com.apple.driver.usb.cdc",
    "com.apple.driver.usb.AppleUSBCommon",
    "com.apple.driver.AppleUSBDeviceAudioController",
    "com.apple.driver.AppleUSBDeviceMux",
    "com.apple.driver.AppleUSBDeviceNCM",
    "com.apple.driver.usb.cdc.ecm",
    "com.apple.driver.usb.ethernet.asix",
    "com.apple.driver.AppleUSBEthernetDevice",
    "com.apple.driver.AppleUSBEthernetHost",
    "com.apple.driver.AppleUSBLightningAdapter",
    "com.apple.driver.AppleUSBMike",
    "com.apple.driver.usb.cdc.ncm",
    "com.apple.driver.usb.networking",
    "com.apple.driver.AppleUVDM",
    "com.apple.driver.AppleUVDMDriver",
    "com.apple.driver.AudioDMACLLTEscalationDetector-Stub",
    "com.apple.driver.AudioDMAController-T8140",
    "com.apple.driver.AudioDMAFamily",
    "com.apple.kec.Compression",
    "com.apple.iokit.CoreAnalyticsFamily",
    "com.apple.kext.CoreTrust",
    "com.apple.driver.DCPAVFamilyProxy",
    "com.apple.driver.DCPDPFamilyProxy",
    "com.apple.iokit.IOMIPIFamily",
    "com.apple.driver.DMAChannelProxy",
    "com.apple.EXBrightKext",
    "com.apple.driver.EXDisplayPipeH17P",
    "com.apple.ExclaveKextClient",
    "com.apple.driver.ExclaveSEPManagerProxy",
    "com.apple.driver.ExclavesAudioKext",
    "com.apple.driver.FairPlayIOKit",
    "com.apple.filesystems.hfs.kext",
    "com.apple.driver.IISAudioIsolatedStreamECProxy",
    "com.apple.iokit.IOAVFamily",
    "com.apple.iokit.IOAccessoryManager",
    "com.apple.iokit.IOAccessoryPortUSB",
    "com.apple.iokit.IOAudio2Family",
    "com.apple.driver.IOAudioCodecs",
    "com.apple.iokit.IOBiometricFamily",
    "com.apple.iokit.IOCECFamily",
    "com.apple.iokit.IOCryptoAcceleratorFamily",
    "com.apple.driver.IODARTFamily",
    "com.apple.iokit.IODisplayPortFamily",
    "com.apple.iokit.IOGPUFamily",
    "com.apple.iokit.IOGameControllerFamily",
    "com.apple.iokit.IOHDCPFamily",
    "com.apple.driver.DiskImages",
    "com.apple.driver.DiskImages.FileBackingStore",
    "com.apple.driver.DiskImages.KernelBacked",
    "com.apple.driver.DiskImages.RAMBackingStore",
    "com.apple.driver.DiskImages.ReadWriteDiskImage",
    "com.apple.driver.DiskImages.UDIFDiskImage",
    "com.apple.iokit.IOHIDFamily",
    "com.apple.driver.IOHIDPowerSource",
    "com.apple.iokit.IOMikeyBusFamily",
    "com.apple.iokit.IOMobileGraphicsFamily-DCP",
    "com.apple.iokit.IOMobileGraphicsFamily",
    "com.apple.iokit.IONVMeFamily",
    "com.apple.iokit.IONetworkFamily",
    "com.apple.iokit.IONetworkingFamily",
    "com.apple.driver.IOPAudioAssetManagerDevice",
    "com.apple.driver.IOPAudioClientManagerDevice",
    "com.apple.iokit.IOPAudioDriverFamily",
    "com.apple.driver.IOPAudioHapticsLEAPControlDevice",
    "com.apple.driver.IOPAudioIOBufferDevice",
    "com.apple.driver.IOPAudioIsolatedIOBufferDevice",
    "com.apple.driver.IOPAudioLEAPControlDevice",
    "com.apple.driver.IOPAudioLPMicDevice",
    "com.apple.driver.IOPAudioPCMAssetManagerDevice",
    "com.apple.driver.IOPAudioVoiceTriggerDevice",
    "com.apple.iokit.IOPCIFamily",
    "com.apple.iokit.IOPortFamily",
    "com.apple.iokit.IOReportFamily",
    "com.apple.iokit.IOSCSIArchitectureModelFamily",
    "com.apple.iokit.IOSCSIBlockCommandsDevice",
    "com.apple.iokit.IOSerialFamily",
    "com.apple.iokit.IOSkywalkFamily",
    "com.apple.driver.IOSlaveProcessor",
    "com.apple.iokit.IOSlowAdaptiveClockingFamily",
    "com.apple.iokit.IOStorageFamily",
    "com.apple.iokit.IOStreamFamily",
    "com.apple.iokit.IOSurface",
    "com.apple.IOTextEncryptionFamily",
    "com.apple.iokit.IOThunderboltFamily",
    "com.apple.iokit.IOTimeSyncFamily",
    "com.apple.iokit.IOUSBDeviceFamily",
    "com.apple.driver.AppleUSBXDCI",
    "com.apple.driver.AppleUSBXDCIARM",
    "com.apple.iokit.IOUSBHostFamily",
    "com.apple.driver.usb.AppleSynopsysUSB40XHCI",
    "com.apple.driver.usb.AppleSynopsysUSBXHCI",
    "com.apple.driver.usb.AppleUSBHostBillboardDevice",
    "com.apple.driver.usb.AppleUSBHostCompositeDevice",
    "com.apple.driver.AppleUSBHostMergeProperties",
    "com.apple.driver.usb.AppleUSBHostPacketFilter",
    "com.apple.driver.usb.AppleUSBHostiOSDevice",
    "com.apple.driver.usb.AppleUSBHub",
    "com.apple.driver.usb.AppleUSBXHCI",
    "com.apple.driver.usb.IOUSBHostHIDDevice",
    "com.apple.iokit.IOUSBMassStorageDriver",
    "com.apple.iokit.IOUserEthernet",
    "com.apple.plugin.IOgPTPPlugin",
    "com.apple.nke.l2tp",
    "com.apple.kec.Libm",
    "com.apple.nke.ppp",
    "com.apple.driver.RTBuddy",
    "com.apple.security.sandbox",
    "com.apple.driver.SecureRTBuddyProxy",
    "com.apple.driver.AudioSharedDARTMapperProxy",
    "com.apple.kec.XrtHostedXnu",
    "com.apple.filesystems.apfs",
    "com.apple.driver.corecapture",
    "com.apple.kec.corecrypto",
    "com.apple.filesystems.lifs",
    "com.apple.driver.mDNSOffloadUserClient-Embedded",
    "com.apple.kec.pthread",
    "com.apple.filesystems.tmpfs",
    # iPhone16,2 specific
    "com.apple.AGXFirmwareKextG16PRTBuddy",
    "com.apple.AGXG16P",
    "com.apple.driver.AppleAOPAD5860",
    "com.apple.driver.AppleAOPVoiceTrigger",
    "com.apple.driver.AppleCS35L27Amp",
    "com.apple.driver.AppleCS42L77Audio",
    "com.apple.driver.AppleMCA2-T8130",
    "com.apple.driver.AppleMobileDispH16P-DCP",
    "com.apple.driver.AppleT8130",
    "com.apple.driver.AppleT8130CLPC",
    "com.apple.driver.AppleT8130PCIe",
    "com.apple.driver.AppleT8130PMGR",
    # t8122 specific
    "AppleMCA2_T8122.kext",
    "AppleT8122.kext",
    "AppleT8122CLPC.kext",
    "AppleT8122PCIe.kext",
    "AppleT8122PCIeC.kext",
    "AppleT8122PMGR.kext",
    "AudioDMAController_T8122.kext",
    # macOS specific (but probably also match iOS)
    "SharedDARTMapperProxy.kext",
]

kernels = [
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/19",
    #     "max": "19.6.0",
    #     "min": "19.0.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_10.15.7_19H1824.kdk/System/Library/Kernels/kernel",
    #     "extensions": "/Library/Developer/KDKs/KDK_10.15.7_19H1824.kdk/System/Library/Extensions/",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/20",
    #     "max": "20.6.0",
    #     "min": "20.0.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_11.7.9_20G1426.kdk/System/Library/Kernels/kernel.release.t8101",
    #     "extensions": "/Library/Developer/KDKs/KDK_11.7.9_20G1426.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/21",
    #     "max": "21.6.0",
    #     "min": "21.0.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_12.5_21G72.kdk/System/Library/Kernels/kernel.release.t8110",
    #     "extensions": "/Library/Developer/KDKs/KDK_12.5_21G72.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/22",
    #     "max": "22.6.0",
    #     "min": "22.0.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_13.6.7_22G720.kdk/System/Library/Kernels/kernel.release.t8122",
    #     "extensions": "/Library/Developer/KDKs/KDK_13.6.7_22G720.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/23",
    #     "max": "23.6.0",
    #     "min": "23.0.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_14.6.1_23G93.kdk/System/Library/Kernels/kernel.release.t8122",
    #     "extensions": "/Library/Developer/KDKs/KDK_14.6.1_23G93.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/24.0/",
    #     "max": "24.1.0",
    #     "min": "24.0.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_15.0_24A335.kdk/System/Library/Kernels/kernel.release.t8122",
    #     "extensions": "/Library/Developer/KDKs/KDK_15.0_24A335.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/24.1/",
    #     "max": "24.2.0",
    #     "min": "24.1.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_15.1.1_24B91.kdk/System/Library/Kernels/kernel.release.t6030",
    #     "extensions": "/Library/Developer/KDKs/KDK_15.1.1_24B91.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/24.2/",
    #     "max": "24.3.0",
    #     "min": "24.2.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_15.2_24C101.kdk/System/Library/Kernels/kernel.release.t8132",
    #     "extensions": "/Library/Developer/KDKs/KDK_15.2_24C101.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/24.3/",
    #     "max": "24.4.0",
    #     "min": "24.3.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_15.3.1_24D70.kdk/System/Library/Kernels/kernel.release.t8132",
    #     "extensions": "/Library/Developer/KDKs/KDK_15.3.1_24D70.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/24.4/",
    #     "max": "24.5.0",
    #     "min": "24.4.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_15.4_24E247.kdk/System/Library/Kernels/kernel.release.t8132",
    #     "extensions": "/Library/Developer/KDKs/KDK_15.4_24E247.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    # {
    #     "target": "com.apple.kernel",
    #     "folder": "kernel/24.5/",
    #     "max": "24.6.0",
    #     "min": "24.5.0",
    #     "kernel": "/Library/Developer/KDKs/KDK_15.5_24F74.kdk/System/Library/Kernels/kernel.release.t8132",
    #     "extensions": "/Library/Developer/KDKs/KDK_15.5_24F74.kdk/System/Library/Extensions",
    #     "skip_list": [],
    # },
    {
        "target": "com.apple.kernel",
        "folder": "kernel/25.0/",
        "max": "25.1.0",
        "min": "25.0.0",
        "kernel": "/Library/Developer/KDKs/KDK_26.0_25A5279m.kdk/System/Library/Kernels/kernel.release.t8132",
        "extensions": "/Library/Developer/KDKs/KDK_26.0_25A5279m.kdk/System/Library/Extensions",
        "skip_list": [],
    },
]


def find_kext(directory, kext):
    re_pattern = re.compile(rf"{kext}$", re.IGNORECASE)
    for root, _, files in os.walk(directory):
        for file in files:
            file_path = os.path.join(root, file)
            if re_pattern.search(file_path):
                return file_path
    return None


if __name__ == "__main__":
    if os.getenv("DO_KEXTS"):
        for k in kernels:
            done = set()
            not_found = set()
            for x in entries:
                kext = x.rsplit(".", 1)[-1]
                if kext == "kext":
                    kext = x.rsplit(".", 2)[-2]
                    print(f"🚨 {x} using {kext} 🚨")
                if kext in k["skip_list"]:
                    continue  # TODO: skip (for now) why are these taking so long? inifiinite loop?
                if kext in done:
                    print(f"⚠️ {x} already done?? (name collision)")

                kext_path = find_kext(k["extensions"], kext)
                if not kext_path:
                    not_found.add(x)
                    continue

                os.environ["TARGET"] = x
                os.makedirs(f"{k["folder"]}/kexts", 0o750, exist_ok=True)
                os.environ["JSON_FILE"] = f"{k["folder"]}/kexts/{kext}.json"
                if os.path.exists(os.environ["JSON_FILE"]):
                    print(f"❌ 🚨 {os.environ["JSON_FILE"]} already exists (overwriting!!) 🚨")
                    continue
                os.environ["MAX_VERSION"] = k["max"]
                os.environ["MIN_VERSION"] = k["min"]
                subprocess.run(
                    [
                        "scripts/run.sh",
                        "--kext",
                        kext_path,
                    ]
                )
                done.add(kext)

            for x in not_found:
                print(f"❌ {x} not found")

    if os.getenv("DO_KERNELS"):
        for k in kernels:
            os.environ["TARGET"] = k["target"]
            os.makedirs(k["folder"], 0o750, exist_ok=True)
            os.environ["JSON_FILE"] = k["folder"] + "/xnu.json"
            os.environ["MAX_VERSION"] = k["max"]
            os.environ["MIN_VERSION"] = k["min"]
            subprocess.run(["scripts/run.sh", "--kernel", k["kernel"]])

    print("✅ Done")
